# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binaryCluster <- function(X, initialNumberOfComponents, numIterations, nDataLevels, nViews, hasNull, fileLocation) {
    .Call('binaryCluster_binaryCluster', PACKAGE = 'binaryCluster', X, initialNumberOfComponents, numIterations, nDataLevels, nViews, hasNull, fileLocation)
}

